trigger:
  - main

parameters:
  - name: parameter1
    type: string
    default: defaultParameter1
  - name: parameter2
    type: string
    default: defaultParameter2
  - name: parameter3
    type: object
    default: []

variables:
  fromParameter1: ${{ parameters.parameter1 }}
  fromParameter2: ${{ parameters.parameter2 }}
  fromParameter3: "${{ convertToJson(parameters.parameter3) }}"

steps:
  - script: echo "${{ convertToJson(parameters.parameter3) }}"

#  - task: FileTransform@1
#    displayName: File transformation template.json
#    inputs:
#      folderPath: $(Build.SourcesDirectory)
#      targetFiles: template.json
#      fileType: json

  - task: replacetokens@5
    displayName: replace tokens
    inputs:
      targetFiles:                '**/*.json'
      tokenPattern:               doublebraces
      verbosity:                  detailed
      actionOnMissing:            fail
      keepToken:                  true
      actionOnNoFiles:            fail
      useAdditionalVariablesOnly: true
      inlineVariables: |-
        fromParameter1: ${{ parameters.parameter1 }}
        fromParameter2: ${{ parameters.parameter2 }}
        fromParameter3: ${{ convertToJson(parameters.parameter3) }}

#  - task: PublishPipelineArtifact@1
#    inputs:
#      targetPath: '$(Build.SourcesDirectory)/template.json'
#      artifactName: template

  - script: cat template.json