trigger:
  - main

parameters:
  - name: parameter1
    type: string
    default: Guava
  - name: parameter2
    type: object
    default: []

steps:
  - task: Bash@3
    displayName: Run JQ replace
    env:
      parameter1: ${{ parameters.parameter1 }}
      parameter2: ${{ parameters.parameter2 }}
    inputs:
      targetType: filePath
      filePath: replace_fruit.sh

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/replaced.json'
      artifactName: replaced

  - script: cat replaced.json